BEGIN;

-- Reproduce three tables that older deployments created before a migration
-- was captured for them, so a fresh installation has them before 018
-- (security_settings) and 021 (operator_access_resets) first use them.
-- Idempotent: on a deployment that already has these tables, every
-- statement below is a no-op.

-- Server-side security mode switches (text values), e.g. relay_guard_mode,
-- read by the API and the relay-guard ops scripts.
CREATE TABLE IF NOT EXISTS security_settings (
    setting_key TEXT PRIMARY KEY,
    setting_value TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by UUID REFERENCES operator_accounts(id)
);

-- Short-lived relay authorization leases issued to Approved managed devices
-- and synced into the relay firewall by rustdesk-relay-guard-sync.
-- id is generated by the application.
CREATE TABLE IF NOT EXISTS relay_access_leases (
    id UUID PRIMARY KEY,
    device_id UUID NOT NULL
        REFERENCES managed_devices(id) ON DELETE CASCADE,
    credential_serial UUID NOT NULL,
    source_ip INET NOT NULL,
    issued_at TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    last_renewed_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    CONSTRAINT relay_access_leases_check
        CHECK (expires_at > issued_at)
);

CREATE INDEX IF NOT EXISTS relay_access_leases_active_idx
    ON relay_access_leases (expires_at)
    WHERE revoked_at IS NULL;

CREATE INDEX IF NOT EXISTS relay_access_leases_device_idx
    ON relay_access_leases (device_id, issued_at DESC);

CREATE INDEX IF NOT EXISTS relay_access_leases_source_idx
    ON relay_access_leases (source_ip, expires_at DESC);

-- One-time operator access-recovery links (Owner-issued or self-service).
-- Only the token hash is stored; id is generated by the application.
-- 021 re-creates operator_access_resets_reset_mode_check by name.
CREATE TABLE IF NOT EXISTS operator_access_resets (
    id UUID PRIMARY KEY,
    account_id UUID NOT NULL
        REFERENCES operator_accounts(id) ON DELETE CASCADE,
    token_hash BYTEA NOT NULL UNIQUE,
    reset_mode TEXT NOT NULL,
    requested_by UUID NOT NULL
        REFERENCES operator_accounts(id),
    reason TEXT NOT NULL,
    source_ip INET,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ,
    used_ip INET,
    revoked_at TIMESTAMPTZ,
    CONSTRAINT operator_access_resets_check
        CHECK (expires_at > created_at),
    CONSTRAINT operator_access_resets_reset_mode_check
        CHECK (reset_mode IN ('password_only', 'totp_only', 'password_totp'))
);

CREATE INDEX IF NOT EXISTS operator_access_resets_account_idx
    ON operator_access_resets (account_id, created_at DESC);

CREATE INDEX IF NOT EXISTS operator_access_resets_active_idx
    ON operator_access_resets (expires_at)
    WHERE used_at IS NULL
      AND revoked_at IS NULL;

COMMIT;
